### ISSUE TITLE
php error in front

### ISSUE THREAD

**Issue by Foine** [novius-os/noviusos_blognews#13]
Hello. I have seen two errors in the fuel logs when the front is displayed :

ERROR ---> 8 - Undefined index: comments in /home/antoine/web/oppoc/novius-os/local/applications/noviusos_blognews/views/front/comment/nb.view.php on line 12
ERROR ---> 8 - Undefined index: comments in /home/antoine/web/oppoc/novius-os/local/applications/noviusos_blognews/classes/controller/front.ctrl.php on line 87

The first one is not displayed when I have my disqus application installed but I think it's because I re-write the "nb.view.php" file.
I don't think it's a big problem, but it's better when there is no "ERROR" in the log.

See you soon !

**Comment by felixgilles** [comment]
The 'comments' key  is defined in the default noviusos_blognews config file  (local/applications/noviusos_blognews/config/config.php). Your app extends this config ? Have you removed the 'comments' key ?

**Comment by felixgilles** [comment]
Hi @Foine, do you resolved your issue ?
